version: "3.9"
services:
  shopapp:
    container_name: shopapp
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/actuator/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      SHOPAPP_ARGS: >-
        --management.endpoint.metrics.enabled=true --management.endpoints.web.exposure.include=* 
        --management.endpoint.prometheus.enabled=true --management.metrics.export.prometheus.enabled=true
        --management.metrics.distribution.percentiles-histogram.http.request.duration=true 
        --management.metrics.distribution.percentiles.http.request.duration=0.5,0.75,0.95,0.99 
        --management.metrics.distribution.sla.http.request.duration=1ms,3ms,5ms,10ms,30ms,50ms,100ms,300ms,500ms,1s,3s,5s
    restart: unless-stopped